# Generated by Django 2.0.6 on 2018-10-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20181023_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('main_balance', models.FloatField()),
                ('emergency_balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.Customer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
