# Generated by Django 2.1.1 on 2018-10-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20181023_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date']},
        ),
    ]
